# Build Stage
FROM eclipse-temurin:25-jdk-alpine AS builder
WORKDIR /app
COPY gradlew .
COPY gradle gradle
COPY build.gradle.kts .
COPY settings.gradle.kts .
COPY . .
RUN chmod +x ./gradlew
# Build only the wallet service
RUN ./gradlew :oenexa-wallet-service:build -x test

# Run Stage
FROM eclipse-temurin:25-jre-alpine
WORKDIR /app
COPY --from=builder /app/oenexa-wallet-service/build/libs/*-SNAPSHOT.jar app.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]
