# Build Stage
FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY oenexa-trading-service/go.mod oenexa-trading-service/go.sum ./
RUN go mod download
COPY oenexa-trading-service/ .
RUN CGO_ENABLED=0 GOOS=linux go build -o trading-service .

# Run Stage
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/trading-service .
EXPOSE 8084
CMD ["./trading-service"]
