server:
  port: 8083

spring:
  application:
    name: oenexa-kyc-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3307}/kyc_db
    username: root
    password: ${MYSQL_PASSWORD:verysecret}
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
  data:
    redis:
      host: localhost
