server:
  port: 8088
spring:
  application:
    name: oenexa-security-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3307}/security_db?createDatabaseIfNotExist=true
    username: root
    password: ${MYSQL_PASSWORD:verysecret}
  kafka:
    bootstrap-servers: localhost:9092
  elasticsearch:
    uris: http://localhost:9200
